### ISSUE TITLE
presque "the right way"

### ISSUE THREAD

**Issue by guillaumeagile** [odinnou/hexagonal-architecture-right-way#1]
y'a des trucs très sympa dans ta propo d'archi mais quel dommage d'utiliser les exceptions alors que c'est maintenant reconnu un anti pattern
pourquoi tu n'utilises pas un Result/Maybe/Optional ? Tellement plus élégant/efficace (et en performance aussi)

**Comment by Dashell** [comment]
> y'a des trucs très sympa dans ta propo d'archi mais quel dommage d'utiliser les exceptions alors que c'est maintenant reconnu un anti pattern pourquoi tu n'utilises pas un Result/Maybe/Optional ? Tellement plus élégant/efficace (et en performance aussi)

Tu entends quoi par Result/Maybe/Optional ? 
Optional si je me trompe pas c'est du java, y'a pas vraiment d'équivalent en .Net

Et tu as des sources qui détaillent/expliquent en quoi c'est un anti pattern ? 
ca m'intéresse !

**Comment by odinnou** [comment]
Hello, j'ai fait pas mal de recherches et j'avoue ne pas avoir trouvé de ressource qui prouve par A+B que l'utilisation d'un IExceptionFilter en ASP.NET (ou encore un ControllerAdvice  + ExceptionHandler en SpringBoot) est un anti-pattern.

D'ailleurs je ne vois pas de contre-indication dans le cas d'une architecture hexagonale, car via cette façon de faire, c'est le driving-adapter qui se charge d'handle (ou non) l'exception soulevée dans les stacks sous-jacentes.

En tout cas, si tu as un article à partager, je suis preneur

**Comment by guillaumeagile** [comment]
Alors,  Result/Maybe/Optional ce sont en fait des Monads
Un truc qui peut faire peur mais en fait, super efficace en terme de code et de lisibilité si tu es habitués au lambda expression (mais avec Linq tu en fais déjà)
Il y a une librairie .Net qui possède tous ces éléments et bien suivie par la communauté.
Je l'utilise dans mes projets
https://github.com/louthy/language-ext#option

**Comment by guillaumeagile** [comment]
Non, juste l'anti pattern c'est d'utiliser les exceptions pour les cas métiers
pour tout ce qui "plantage" du système, il faut laisser les exceptions remonter dans ton filtre
j'aime bien cet article, très complet sur le sujet
https://newdevsguide.com/2022/11/06/exception-anti-patterns-in-csharp/
et le conseil #7
#7: Using Exceptions for Flow Control

**Comment by odinnou** [comment]
Merci pour toutes ses réponses
Très instructif, concernant language-ext, j'ai eu une expérience très cool avec vavr en Java et je retrouve bien cette philosophie dans cette lib.

Et en effet si on se fie au simple terme "Exception", l'utiliser à tort et à travers semble en effet un anti-pattern
Je vais voir comment modifier le projet pour en tenir compte.

Encore un grand merci @guillaumeagile  !
